//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.235
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Willcraftia.Content.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Willcraftia.Content.Studio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Do you want to delete this file?
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDeleteFile {
            get {
                return ResourceManager.GetString("ConfirmDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete this folder from the project?
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDeleteFileFromProject {
            get {
                return ResourceManager.GetString("ConfirmDeleteFileFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete this folder?
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDeleteFolder {
            get {
                return ResourceManager.GetString("ConfirmDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to override the existing file?
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmOverrideFile {
            get {
                return ResourceManager.GetString("ConfirmOverrideFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The project file is modified.
        ///Do you want to save this? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmSaveProjectFile {
            get {
                return ResourceManager.GetString("ConfirmSaveProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleConfirmation {
            get {
                return ResourceManager.GetString("TitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleCreateFolder {
            get {
                return ResourceManager.GetString("TitleCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleOpenProject {
            get {
                return ResourceManager.GetString("TitleOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Plugin Assembly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSelectPluginAssembly {
            get {
                return ResourceManager.GetString("TitleSelectPluginAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Project File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSelectProjectFile {
            get {
                return ResourceManager.GetString("TitleSelectProjectFile", resourceCulture);
            }
        }
    }
}
